files:
  - source: /bin/lang/crowdin/template.xml
    translation: /bin/lang/crowdin/freac_%osx_locale%.xml
    languages_mapping:
      osx_locale:
        en_GB: en_UK
        sr_Latn: sr
        sr_Cyrl: sr@Cyrl
        zh-Hans: zh_CN
        zh-Hant: zh_TW
        val: ca@valencia
    content_segmentation: '0'
    translatable_elements:
      - /LangFile/info/property
      - /LangFile/data/entry
      - /LangFile/data//entry
